"use strict";
var actions_1 = require('./actions');
exports.addStudent = actions_1.addStudent;
exports.newName = actions_1.newName;
exports.receiveStudents = actions_1.receiveStudents;
exports.fetchStudents = actions_1.fetchStudents;
var component_1 = require('./component');
exports.Students = component_1.Students;
var reducer_1 = require('./reducer');
exports.students = reducer_1.students;
